config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  
  resources :users do
    member do
      get :profile
    end
  end
  get 'users/update'
  patch 'users/update'

  resources :rooms do
    collection do
      get :search
    end
  end


  root to: "start_pages#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show edit]
  resources :rooms, only: %i[index new create show] do
    resources :reservations, only: %i[index create show], shallow: true
    match '/reservations/new', to: 'reservations#new', via: 'post'
    match '/reservations/new', to: 'reservations#new', via: 'patch'
  end
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to image_tag('logo.png', class:'navbar-brand'), root_path %>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">

        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "登録する", new_user_registration_path, class: 'btn btn- secondary nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h2>©︎ 2022 POTEPAN.INC.</h2>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-inner">
    <nav class='navbar navbar-expand-lg navigation navbar-light bg-dark'>
      <div class="header-left-nav">
        <%= link_to image_tag('logo.png', class:'navbar-brand'), root_path %>
        <div class="header-serch d-lg-inline-block d-none">
          <%= search_form_for @q, url: search_rooms_path do |f| %>
            <%= f.search_field :address_cont, placeholder: 'エリア' %>
          <% end %>
        </div>
        <div class="header-serch d-lg-inline-block d-none">
          <%= search_form_for @q, url: search_rooms_path do |f| %>
            <%= f.search_field :name_or_introduction_or_address_cont, placeholder: 'キーワード' %>
          <% end %>
        </div>
        <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
          aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
          <span class='navbar-toggler-icon'></span>
        </button>
      </div>
      <div class='collapse navbar-collapse' id='navbarSupportedContent'>
        <ul class='navbar-nav ml-auto main-nav align-items-center'>
          <li class='nav-item'>
            <%= current_user.decorate.full_name %><!--ここにuserの名前を入れる, decoratorの導入もあり -->
          </li>

          <li class='nav-item dropdown dropdown-slide'>
            <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
              <!-- <%= image_tag 'default_icon.jpg', class: 'rounded-circle mr15', size: '40x40' %> -->
              <% if @user.user_image.blank? %>
                <%= image_tag 'default_icon.jpg', class: 'rounded-circle mr15', size: '40x40'  %>
              <% else %>
                <%= image_tag @user.user_image.url, class: 'rounded-circle mr15', size: '40x40' %> 
              <% end %>
            </a>
            <div class='dropdown-menu dropdown-menu-right'>
              <div class='dropdown-divider'></div>
              <%= link_to "ルーム登録", new_room_path, class: 'dropdown-item' %>
              <%= link_to "予約済みルーム一覧", room_reservations_path(current_user), class: 'dropdown-item' %> 
              <%= link_to "登録済みルーム一覧", rooms_path, class: 'dropdown-item' %> 
              <%= link_to "設定", user_path(current_user), class: 'dropdown-item' %>
              <%= link_to "ログアウト", logout_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>