config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  
  resources :users do
    member do
      get :profile
    end
  end
  get 'users/update'
  patch 'users/update'

  resources :rooms do
    collection do
      get :search
    end
  end


  root to: "start_pages#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show edit]
  resources :rooms, only: %i[index new create show] do
    resources :reservations, only: %i[index create show], shallow: true
    match '/reservations/new', to: 'reservations#new', via: 'post'
    match '/reservations/new', to: 'reservations#new', via: 'patch'
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_people, presence: true, numericality: {only_integer: true, greater_than: 0}

  validate :date_before_start
  validate :date_before_end



  def date_before_start
    if start_date.present? && end_date.present? && start_date < Date.today
      errors.add(:start_date, "は今日以降のものを選択してください") if start_date < Date.today     
    end
  end

  def date_before_end
    if start_date.present? && end_date.present? && start_date >= end_date
      errors.add(:end_date, "は開始日以降のものを選択してください") if end_date < start_date
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new

    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:room_id])
    
    render 'rooms/show' if @reservation.invalid?
    
  end

  def create
    @reservation = current_user.reservations.build(reservation_params)
    #@reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    #@total_rate = @reservation.room.single_rate * @reservation.number_of_people * (@reservation.end_date - @reservation.start_date).to_i
    #@reservation = current_user.reservations.build(reservation_params)
    # room_idの情報はフォームから送られないので、deviseのメソッドで追加
    #@reservation.user_id = current_user.id
    if @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservation_path(@reservation.room.id)
    else
      @room = Room.find(params[:reservation][:room_id])
      @user = User.find(params[:reservation][:user_id])
      render "rooms/show"
    end

  

  end

  def show 
    @reservation = Reservation.find(params[:id])
    @room = Room.find(params[:id])
    #@reservationからroomのnameを出力しようとすると同じ部屋名しか出てこなかったのでRoomモデルでインスタンスを作成し@roomに代入。ルーティングでreservation/showではreservation/:idだったのでURLのidからRoom情報を取得してきている。
  end

  private
  

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :number_people, :total_price, :room_id, :user_id, :price)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: [room, reservation], url: room_reservations_new_path(room), local: true do |f| %>
      <%= render 'shared/error_messages', obj: f.object %>
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control mb-3 order-date-form', min: Date.current, placeholder: "年/月/日" %>
      
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control mb-3 order-date-form', min: Date.current, placeholder: "年/月/日" %>
      
      <%= f.label :number_people %>
      <%= f.number_field :number_people, class: 'form-control mb-3 order-date-form' %>
      
      <%= f.hidden_field :room_id, value: room.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :price, value: room.price %>
      
      <%= f.submit "確認画面へ", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>

    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td>
            <% if reservation.room.room_image.blank? %>
              <%= image_tag 'default_room.jpg', class: 'card-img-top img-fluid' %>
            <% else %>
              <%= image_tag reservation.room.room_image.url,class: 'card-img-top img-fluid' %> 
            <% end %>
          </td>
          <td><%= link_to reservation.room.name, {controller: 'rooms', action: 'show', id: reservation.room.id}  %></td>
          <td><%= reservation.room.introduction %></td>
          <td><%= reservation.total_price %></td>
          <td><%= reservation.start_date %></td>
          <td><%= reservation.end_date %></td>
          <td><%= reservation.created_at.strftime('%Y年%m月%d日 %H:%M') %></td>
        </tr>
      <% end %>    
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<%= form_with model: [@room, @reservation], method: :post, local: true do |f| %>
  <%= render 'shared/error_messages', obj: f.object %>

  <h1>予約内容確認</h1>

  <ol class="nav">
    <li>1.入力</li>
    <li class="current">2.確認</li>
    <li>3.完了</li>
  </ol>

  <h3>¥<%= @reservation.room.price %>/日</h3>

  <%= f.label :start_dat,"開始日" %>
  <%= f.text_field  :start_date, class: "form_control", readonly: true %>

  <%= f.label :end_date, "終了日" %>
  <%= f.text_field  :end_date, class: "form_control", readonly: true %>

  <h6>使用日数： <%= (@reservation.end_date - @reservation.start_date).to_i  %></h6>
  <!-- start_dateとend_dateのデータ型がDatetime型になっていた。その状態で上記の計算を行うとわけわからん数字になる。なのでデータ型を変更してみた結果うまく動いた。 -->
  <h6>人数：<%= @reservation.number_people %></h6>

  <%= f.label :total_price, "合計金額" %>
  <%= f.text_field  :total_price, class: "form_control", readonly: true, value: (@reservation.price * @reservation.number_people * (@reservation.end_date - @reservation.start_date).to_i) %>

  
  
  <%= f.hidden_field  :room_id, class: "form_control" %>
  
  <%= f.hidden_field  :user_id, class: "form_control" %>
  
  <%= f.hidden_field  :number_people, class: "form_control" %>

  

  <p>上記内容でよろしければ「予約を確定」を押してください</p>

  
  <%= link_to "ルーム詳細に戻る", room_path(@room.id)  %>

  <%= f.submit '予約を確定' %> 
<% end %>

app/views/reservations/show.html.erb
<div class="notifications">
  <div class="notice">Reservation was successfully created.</div>

</div>
<p id="notice">Reservation was successfully created.</p>

<div class="container-fiuld user"> 
  <div class="row">
      <div class="col-md-12 user-view">
          <div class="user-view-box">
              <div class="update-content">
                  <div class="row">
                      <label class="col-md-3" for="room">予約した部屋</label>
                      <div class="col-md-9">
                        <%= link_to @room.name, room_path %>
                      </div>
                  </div>
              </div>
              <div class="update-content">
                  <div class="row">
                      <label class="col-md-3" for="start_date">開始日</label>
                      <div class="col-md-9"><%= @reservation.start_date %></div>
                  </div>
              </div>
              <div class="update-content">
                  <div class="row">
                      <label class="col-md-3" for="end_date">終了日</label>
                      <div class="col-md-9"><%= @reservation.end_date %></div>
                  </div>
              </div>
              <div class="update-content">
                  <div class="row">
                      <label class="col-md-3" for="end_date">価格</label>
                      <div class="col-md-9"><%= @reservation.total_price %></div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>